#!/usr/bin/bash
mkdir $1
cp lib/* $1/
cp .template/template.c $1/$2.c
cd $1
sed 's/EXE =/EXE = '$2'/g' ../.template/Makefile | sed 's/OBJS =/OBJS = '"$(ls *c | sed 's/c$/o/g' | tr '\n' ' ')"'/g' > Makefile
